version: '2'
services:
  ethboot:
    image: y12docker/dltdojo-ethgo
    command: '/start.sh boot'
    ports:
     - "8545:8545"
  ethpeer:
    image: y12docker/dltdojo-ethgo
    command: '/start.sh peer ethboot'
  ethdev:
    image: y12docker/dltdojo-ethgo
    command: '/start.sh dev'
