version: '2'
services:
  btcp:
    image: y12docker/dltdojo-bitcoin
    expose:
      - '18332'
      - '18333'
    command: '/start.sh -regtest -txindex -port=18333 -conf=/opt/btc/bitcoin.conf -datadir=/opt/btc/data -rpcport=18332 -rpcallowip=DLTDOJOSUBNETinSTARTSH -addnode=btcp:18333'
  btcp1:
    extends: btcp
    ports:
      - "127.0.0.1:18332:18332"
      - "127.0.0.1:18333:18333"
  btcp2:
    extends: btcp

  dltdojo:
    image: y12docker/dltdojo
    command: 'start'
