# Distributed Ledger Technology Dojo (DLTDOJO) 
# https://github.com/y12studio/dltdojo
# Dltdojo peers yml file , name:1a  btc peers:4
# DATETIME:2017-01-24T03:03:26.057Z
version: '2'
services:
  btcp0:
    image: y12docker/dltdojo-bitcoin
    expose:
      - '18332'
      - '18333'
    command: '/start.sh -regtest -txindex -port=18333 -conf=/opt/btc/bitcoin.conf -datadir=/opt/btc/data -rpcallowip=DLTDOJOSUBNETinSTARTSH -rpcport=18332 -addnode=btcp0:18333'
  btcp1:
    extends: btcp0
    hostname: btcp1
  btcp2:
    extends: btcp0
    hostname: btcp2
  btcp3:
    extends: btcp0
    hostname: btcp3
  btcp4:
    extends: btcp0
    hostname: btcp4
  dltdojo:
    image: y12docker/dltdojo
    command: start
