# Distributed Ledger Technology Dojo (DLTDOJO) 
# https://github.com/y12studio/dltdojo
# BitcoinCore peers yml file ,name:lv1, peers:4
# DATETIME:2017-01-17T01:36:10.006Z
version: '2'
services:
  dltdojo:
    image: y12docker/dltdojo
    command: start
  btcp:
    image: y12docker/dltdojo-bitcoin
    expose:
      - '18332'
      - '18333'
    command: '/start.sh -regtest -txindex -port=18333 -conf=/opt/btc/bitcoin.conf -datadir=/opt/btc/data -rpcallowip=DLTDOJOSUBNETinSTARTSH -rpcport=18332 -addnode=btcp:18333'
  btcp1:
    extends: btcp
    hostname: btcp1
  btcp2:
    extends: btcp
    hostname: btcp2
  btcp3:
    extends: btcp
    hostname: btcp3
  btcp4:
    extends: btcp
    hostname: btcp4
