version: '2'
services:
  btcboot:
    image: y12docker/dltdojo-bitcoin
    command: '/start.sh'
  cert:
     image: y12docker/dltdojo-blockcerts
     command: '/start.sh'
  abe:
    image: y12docker/dltdojo-abe
    command: '/start.sh'
    ports:
        - "12750:12750"
  jorexp:
    image: y12docker/dltdojo-jorexp
    command: '/start.sh'
    ports:
        - "12751:8080"
